#!/bin/bash

# front_back
colour_gry="\x01" # lys grå front/mellem grå back
colour_wht="\x02" # hvid front/lys blå back
colour_dgry="\x04" # hvid front/mellem grå back
colour_blk="\x05" # mellem grå front/mørke blå back
colour_red="\x06" # lås grå front/mørke blå back
orange_morkblaa="\x07" # lys blå front/mellem grå back
sort_orange="\x08" # mellem grå front/mørke blå back
lysblaa_orange="\x09"
hvid_lysblaa="\x0a"
koks_lysblaa="\x0b"
hvid_koks="\x0c"
snot_koks="\x0d"
sort_snot="\x0e"


#${lysblaa_morkblaa}${hvid_lysblaa}

print_online() {
  online="$(ping -c 1 -q google.com >/dev/null 2>&1 && echo ONLINE || echo OFFLINE)"
  echo -ne "${orange_morkblaa}${sort_orange} ${online}"
}

print_somafm() {
	somafm="$(echo ~/.somafm)"
	echo -ne "${colour_gry}
}

print_volume() {
  volume="$(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')"
  echo -ne "${lysblaa_orange}${hvid_lysblaa} VOL:${volume}% "
}

print_wifi() {
	essid="$( iwgetid | awk '{ print $2 }' | sed 's/ESSID:"//' | sed 's/"//' )"
	echo -ne "${snot_koks}${sort_snot} ${essid} "
}

print_bat() {
    BATT=$( acpi -b | sed 's/.*[charging|unknown], \([0-9]*\)%.*/\1/gi' )
    STATUS=$( acpi -b | sed 's/.*: \([a-zA-Z]*\),.*/\1/gi' )
    if ([ $BATT -le 5 ] && [ $STATUS == 'Discharging' ]); then
        # Beep
        echo -e "\007" >/dev/tty10 && sleep 0.2
        echo -e "\007" >/dev/tty10 && sleep 0.2
        echo -e "\007" >/dev/tty10 && sleep 0.2
        # Blink
        echo 'on' > /proc/acpi/ibm/light && sleep 1
        echo 'off' > /proc/acpi/ibm/light
    fi
  echo -ne "${koks_lysblaa}${hvid_koks} ${BATT}% ${STATUS} "
}

while true; do
	xsetroot -name "$(print_online) $(print_volume) $(print_bat) $(print_wifi)"
  sleep 60
done
